server:
  port: 5033

powsybl-ws:
  database:
    host: localhost

spring:
  rabbitmq:
    addresses: localhost

gridsuite:
  services:
    directory-server:
      base-uri: http://localhost:5026
    user-identity-server:
      base-uri: http://localhost:5034